version: "3"

services:
  db:
    image: postgres:12.2-alpine
    volumes:
      - ./postgres_data/psql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: glean_dev
      POSTGRES_USER: glean
      POSTGRES_PASSWORD: qwerty
  redis:
    image: "redis"
    ports:
      - "6379:6379"
