HTTPServer:
  ListenAddress: '127.0.0.1'
  Port: 9000
  GracefulTimeout: '30s'
  ReadTimeout: '30m'
  WriteTimeout: '5m'
  IdleTimeout: '15m'
Logger:
  EnableConsole: true
  ConsoleJSONFormat: true
  ConsoleLevel: 'debug'
  EnableFile: false
Database:
  Master: 'user=glean password=qwerty dbname=glean_dev host=localhost port=5432 sslmode=disable'
  Replica: 'user=glean password=qwerty dbname=glean_dev host=localhost port=5432 sslmode=disable'
Redis:
  Endpoint: 'localhost:6379'
  Timeout: 10
  MaxIdle: 10
